import Script from 'next/script'
import { Poppins } from 'next/font/google'
import './globals.css'
import './globals.css'
import './styles/bootstrap.min.css'
import './styles/common.css'
import './styles/main.css'
import './styles/responsive.css'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
})

export const metadata = {
  title: 'BuddyScript',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        {children}

        <Script
          src="/assets/js/bootstrap.bundle.min.js"
          strategy="beforeInteractive"
        />

        {/* <Script src="/assets/js/custom.js" strategy="afterInteractive" /> */}
      </body>
    </html>
  )
}
